---
title: "r2d3"
author: "Karim Mezhoud"
date: "`r Sys.Date()`"
output:
  html_document:
    code_folding: show
    toc: true
    number_sections: true
    fig_caption: true
    highlight: tango
runtime: shiny
always_allow_html: true
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(shiny)
library(r2d3)

ui <- fluidPage(
  inputPanel(
    sliderInput("bar_max", label = "Max:",
                min = 0.1, max = 1.0, value = 0.2, step = 0.1)
  ),
  d3Output("d3")
)

server <- function(input, output) {
  output$d3 <- renderD3({
    r2d3(
      runif(5, 0, input$bar_max),
      script = system.file("examples/baranims.js", package = "r2d3")
    )
  })
}

shinyApp(ui = ui, server = server)
```



```{r}
r2d3(data = matrix(round(runif(16, 1, 10000)), ncol = 4, nrow = 4), 
     script = "../inst/examples/chords/chords.js")
```


```{r}
r2d3(data=c(10, 30, 40, 35, 20, 10), 
     script = "../inst/examples/r2d3/barchart.js", 
     container = "div")
```


```{r}
r2d3(
  data=c(0.3, 0.6, 0.8, 0.95, 0.40, 0.20), 
  script = "../inst/examples/r2d3/barchart.js", 
  options = list(color = "orange")
)
```


```{d3 data=c(0.3, 0.6, 0.8, 0.95, 0.40, 0.20)}
// !preview r2d3 data=c(0.3, 0.6, 0.8, 0.95, 0.40, 0.20)

var barHeight = Math.floor(height / data.length);

svg.selectAll('rect')
  .data(data)
  .enter().append('rect')
    .attr('width', function(d) { return d * width; })
    .attr('height', barHeight)
    .attr('y', function(d, i) { return i * barHeight; })
```

```{d3 data=c(10, 30, 40, 35, 20, 10), container="div"}
// !preview r2d3 data=c(10, 30, 40, 35, 20, 10), container="div"

var bars = div
  .selectAll("div")
  .data(data);
    
bars.enter().append("div")
  .style("width", function(d) { return 4 + d * 10 + "px"; })
  .style("background-color", "steelblue")
  .style("border", "1px solid white")
  .style("color", "white")
  .style("padding-left", "2px")
  .text(function(d) { return d; });
```

